(load "lib/test-manager/load.scm")

(load "exercises/chapter-1/exercise-1.scm")
(load "exercises/chapter-1/exercise-3.scm")
(load "exercises/chapter-1/exercise-4.scm")
(load "exercises/chapter-1/exercise-7.scm")
(load "exercises/chapter-1/exercise-8.scm")
(load "exercises/chapter-1/exercise-10.scm")
(load "exercises/chapter-1/exercise-11.scm")
(load "exercises/chapter-1/exercise-12.scm")
