(define (better-smallest-divisor n)
  (define (next d)
    (if (= d 2)
        3
        (+ d 2)))
  (define (find-divisor n test-divisor)
    (cond ((> (square test-divisor) n) n)
          ((divides? test-divisor n) test-divisor)
          (else (find-divisor n (next test-divisor)))))
  (define (divides? a b)
    (= (remainder b a) 0))
  (find-divisor n 2))

(define (better-timed-prime-test n)
  (define (start-prime-test n start-time)
    (if (prime? n)
      (- (runtime) start-time)
      0))
  (define (prime? n)
    (= n (better-smallest-divisor n)))
  (start-prime-test n (runtime)))

(define (better-search-for-primes minimum maximum time)
  (cond ((= minimum maximum) time)
        (else (better-search-for-primes (+ minimum 1) maximum (+ time (better-timed-prime-test minimum))))))
