(define (fast-search-for-primes minimum maximum time)
  (define (fast-timed-prime-test n)
    (define (fermat-test n)
        (define (try-it a)
              (= (expmod a n n) a))
          (try-it (+ 1 (random (- n 1)))))
    (define (fast-prime? n times)
      (cond ((= times 0) true)
            ((fermat-test n) (fast-prime? n (- times 1)))
            (else false)))
    (define (start-prime-test n start-time)
      (if (fast-prime? n 1000)
        (- (runtime) start-time)
        0))
    (start-prime-test n (runtime)))

  (cond ((= minimum maximum) time)
        (else (fast-search-for-primes (+ minimum 1) maximum (+ time (fast-timed-prime-test minimum))))))
